services:
  - type: web
    name: scholarship-recommender
    env: python
    buildCommand: pip install -r requirements_simple.txt
    startCommand: gunicorn web_app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9